### PR TITLE
Upgrade to Django 3

### PR DESCRIPTION
**Pull request by stefankoegl**
https://www.djangoproject.com/weblog/2019/sep/10/django-30-alpha-1-released/

https://docs.djangoproject.com/en/dev/releases/3.0/

- [x] django.utils.six - Remove usage of this vendored library or switch to [six](https://pypi.org/project/six/). --  django-celery-beat 1.4.0 still imports six from there. Try upgrade to 1.5.0 or try to monkey-patch.
- [x] DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working (36dfd454cc8f627191f9a216907d078794d45fd5)
- [x] RemovedInDjango40Warning: django.utils.translation.ugettext() is deprecated in favor of django.utils.translation.gettext().
- [x] RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
- [x] DeprecationWarning: invalid escape sequence \w
- [x] DeprecationWarning: invalid escape sequence \(
- [x] DeprecationWarning: invalid escape sequence \.
- [x] DeprecationWarning: invalid escape sequence \?
- [x] DeprecationWarning: invalid escape sequence \&
- [x] RemovedInDjango40Warning: force_text() is deprecated in favor of force_str(). (mfogel/django-timezone-field#58)
- [x] DeprecationWarning: Please use assertEqual instead.
- [x] DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
- [x] RemovedInDjango40Warning: django.utils.translation.ungettext() is deprecated in favor of django.utils.translation.ngettext().

### CODE REVIEW

**Comment by SiqingYu** [comment]
I read the [Django 3.0 release notes](https://docs.djangoproject.com/en/3.0/releases/3.0) and found some changes to pay attention to:
- [ ] [Model.save() when providing a default for the primary key](https://docs.djangoproject.com/en/3.0/releases/3.0/#model-save-when-providing-a-default-for-the-primary-key)
- [ ] [urlencode() now encodes iterable values as they are when doseq=False, rather than iterating them, bringing it into line with the standard library urllib.parse.urlencode() function.
](https://docs.djangoproject.com/en/3.0/releases/3.0/#miscellaneous)
- [ ] [RegexPattern, used by re_path(), no longer returns keyword arguments with None values to be passed to the view for the optional named groups that are missing.
](https://docs.djangoproject.com/en/3.0/releases/3.0/#miscellaneous)

I'm not sure about the effects of changes above on mygpo. I need some time to double-check.

**Comment by SiqingYu** [comment]
- [ ] Code review
- [ ] Check https://github.com/gpodder/mygpo/pull/247#issue-315978938
- [ ] Check https://github.com/gpodder/mygpo/pull/247#issuecomment-575719093

**Comment by stefankoegl** [comment]
> I read the Django 3.0 release notes and found some changes that may require attention:

Thanks for pointing those out! I had a quick look and I think those should not be an issue. 

Also the two open items from the issue description do not necessarily be addressed in this pull request. I think they originate in some dependencies, and will not cause any issues in the currently used Python / Django versions.

**Comment by stefankoegl** [comment]
> Model.save() when providing a default for the primary key

We never provide a default value for the primary key.

> urlencode() now encodes iterable values as they are when doseq=False, rather than iterating them, bringing it into line with the standard library urllib.parse.urlencode() function.

We only use `urllib.parse.urlencode()`, never Django's own version.


> RegexPattern, used by re_path(), no longer returns keyword arguments with None values to be passed to the view for the optional named groups that are missing.

We don't rely on that behavior anywhere.

**Pull request merged**
