### PR TITLE
wait for postgres + check db initialized

### PR DESCRIPTION
**Pull request by elelay**
used in containers depending on postresql readiness.
No need for full psql command: the simple psql.py script is enough.

Now they all wait on container postgres_1, but I'm facing an error message in worker: `unknown command celery`
```
worker_1     | Unknown command: 'celery'
worker_1     | Type 'manage.py help' for usage.
mygpodocker_worker_1 exited with code 1
```

When I modify the command to call manage.py help, there is no mention of celery:
```
 Type 'manage.py help <subcommand>' for help on a specific subcommand.
 
 Available subcommands:
 
 [auth]
     changepassword
     createsuperuser
 
 [contenttypes]
     remove_stale_contenttypes
 
 [data]
     feed-downloader
     group-podcasts
     tag-downloader
 
 [directory]
     category-merge-spellings
     update-toplist
 
 [django]
     check
     compilemessages
     createcachetable
     dbshell
     diffsettings
     dumpdata
     flush
     inspectdb
     loaddata
     makemessages
     makemigrations
     migrate
     opbeat
     sendtestemail
     shell
     showmigrations
     sqlflush
     sqlmigrate
     sqlsequencereset
     squashmigrations
     startapp
     startproject
     test
     testserver
 
 [publisher]
     make-publisher
 
 [sessions]
     clearsessions
 
 [staticfiles]
     collectstatic
     findstatic
     runserver
```

### CODE REVIEW

**Comment by stefankoegl** [comment]
Looks great! Some comments:

* Is there any particular reason why you need both a shell script and a python script? I guess it would be possible to do all in one of them, right?
* I have just updated the `docker` branch, and have fixed the commands for the celery services (`worker` and `beat`). That should resolve your issue.
* Do you know why the tests for the pull request are failing? I don't see any change that would cause these errors, and the `docker` branch itself builds correctly.

**Comment by elelay** [comment]
I've started with the bash script from docker docs and wrote the python script to not have to install psql.
It's possible to:
 - keep the bash script and install psql in the docker container (it's not available currently)
 - keep the python script and implement sleep and command line argument pass-through + exec

**Comment by elelay** [comment]
Re failed tests: this build downloaded psycopg2cffi 2.7.6, the successful one 2.7.7 and the error in during psycopg2cffi, so I think it's a version issue.

**Comment by stefankoegl** [comment]
> I've started with the bash script from docker docs and wrote the python script 
> to not have to install psql. It's possible to: [...]

I think either of the two options would be fine, but generally I'd prefer to have just one of the two scripts that does all of the work in one place.

**Comment by elelay** [comment]
@stefankoegl  I've switched the wrapper script to python and have been able to also check for table initialization.
Now the service starts cleanly with:
```
> docker-compose run web /srv/mygpo/contrib/wait-for-postgres.py python manage.py migrate
> docker-compose up
```

**Comment by elelay** [comment]
@stefankoegl I've added an nginx proxy+static file server in this branch: [docker-nginx-front](https://github.com/elelay/mygpo/tree/docker-nginx-front).
Now mygpo renders fine.
Next issue is with registration: needs an smtp server.

**Comment by elelay** [comment]
Regarding failed Travis builds, it looks like psycopg2cffi doesn't build with python 3.7+

**Comment by stefankoegl** [comment]
> Regarding failed Travis builds, it looks like psycopg2cffi doesn't build with python 3.7+

I've opened chtd/psycopg2cffi#95 for that. I'll have a look at the other changes soon.

**Comment by JeanFred** [comment]
@elelay 
> I've added an nginx proxy+static file server in this branch: docker-nginx-front.

Is that needed? In cdcb34f8 I added Whitenoise in front which should be enough to serve static assets ?

**Comment by elelay** [comment]
@JeanFred please see for yourself if possible: when running `docker-compose up` and accessing `http://localhost:8000` I was not seeing any image.
Maybe this is a regression since your work. I'll investigate further...

**Comment by JeanFred** [comment]
@elelay 
> please see for yourself if possible: when running docker-compose up and accessing http://localhost:8000 I was not seeing any image.
> Maybe this is a regression since your work. I'll investigate further...

I’ll try to have a look at this, don’t worry about it − it may have been broken anywhere in the meantime :) (re-reading my first comment, it was a bit unhelpful − I could have just checked myself :)

**Comment by stefankoegl** [comment]
What's the status on this? I'd like to merge this into the docker branch soon (and subsequently merge that one into master), to avoid that they drift apart too much.

**Comment by elelay** [comment]
@stefankoegl AFAIK this PR is ready to merge into the docker branch.
I'll open a new PR for the nginx proxy later. I've not looked at it since JeanFred comment.

**Comment by stefankoegl** [comment]
Thanks :)

**Pull request merged**
