### PR TITLE
Added full Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**
Translated using Transifex:
https://www.transifex.com/yaron/gpodder/

I'm not 100% sure about the "weeks, days, hours" strings at the end, the might crash the app so if needed I'll change this although this is the preferred native form for Hebrew speakers.

Fully compatible with the AntennaPod translation.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Thanks for the translation, and for setting up the Transifex project.

I'm not sure about the pricing of Transifex, but would it be possible to add the other languages (and myself) to the project?

**Comment by yarons** [comment]
@stefankoegl It's free for open source projects, you just need to prove that this is the actual license by providing the repository for inspection, their tool usually finds the license through the repo and verifies that this is indeed an open source license (I've already gone through this process).

I will test the translation, since Hebrew is written from right to left I may also need to assist with converting the CSS accordingly (There are special CSS attributes for that, needs further adjustment after applying).

**Comment by yarons** [comment]
There are many strings still appear in English like the main page, the "Logout" item in the top right menu, the names of the fields in the preferences and several others.

I can't remember translating them so these are non translatable to begin with. :)

The lack of proper CSS adjustment causes some of the text to break due to mixed sentenced (English term within and English sentence for example).

**Comment by yarons** [comment]
There are many strings still appear in English like the main page, the "Logout" item in the top right menu, the names of the fields in the preferences and several others.

I can't remember translating them so these are non translatable to begin with. :)

The lack of proper CSS adjustment causes some of the text to break due to mixed sentenced (English term within and English sentence for example).

**Comment by stefankoegl** [comment]
I'll have a look at the missing translations.

Can you point me to some information on which CSS adjustments are necessary? I'd like to read up on that.

**Comment by yarons** [comment]
Sure, this site explains it pretty well.
Hebrew (like Arabic and Farsi) is written from right to left, so you might think the following sentence starts with a period but in fact it's read from the opposite direction and should also be aligned accordingly:
<div dir="rtl">שלום סטפן.</div>

Assuming this is the case then the whole website should be aligned differently, exactly for this purpose there are 2 methods: `dir="rtl"` and `style=direction:rtl`, the problem is that if you explicitly set things in a certain place (float, or setting the alignment or margin with pixels, we need to adjust that too).

The most common way is to assign an additional CSS sheet where all the modified definitions have `!important` at the end, this way these override the current definition.

A simple test for you would be openning the inspection tool while looking at gpodder.net and just adding one of the attributes I've mentioned earlier (`dir=rtl`…), assuming it should all be mirrored perfectly you might experience glitches and overrides.

Another article that sums it up pretty well is: https://themetry.com/rtl-stylesheets/

I'm willing to assist as much as I can, I may just need your help adding the code to apply a special RTL sheet when Hebrew is displayed.

**Pull request merged**
