### PR TITLE
OpenAPI

### PR DESCRIPTION
**Pull request by SiqingYu**
Based on works from https://github.com/gpodder/mygpo/pull/122

- [x] Update openapi.yaml​ (no API update since V2.11)

### CODE REVIEW

**Comment by dellagustin** [comment]
Hi, sorry, I don't know what DRF stands for, can you explain or give me a reference?

**Comment by SiqingYu** [comment]
> Hi, sorry, I don't know what DRF stands for, can you explain or give me a reference?

Schemas - Django REST framework
https://www.django-rest-framework.org/api-guide/schemas/

**Comment by SiqingYu** [comment]
We might migrate to DRF in the future. But for now, we can release OpenAPI without DRF.

**Comment by SiqingYu** [comment]
I reverted the two latest commits by @dellagustin. As per discussions in https://github.com/gpodder/mygpo/pull/122, we need a seperate place for OpenAPI documentation. I opened a new issue https://github.com/gpodder/mygpo/issues/362 for Swagger UI hosting. For now, let's put the raw openapi.yaml in the repository.

**Comment by dellagustin** [comment]
I advise keeping `openapi.yaml` on the repository for source control over the API specification, you may want to host it somewhere else for other reasons, but as it is part of the API documentation, I believe that file should live originally in the repo together with the rest of the code.
Do you see it differently?

**Pull request merged**
