### PR TITLE
Remove `subscribers_last_week` field from directory API.

### PR DESCRIPTION
**Pull request by SiqingYu**
Addressing https://github.com/gpodder/mygpo/issues/375

### CODE REVIEW

**Comment by ByteHamster** [comment]
The XML API needs to be updated, too, I think

**Comment by SiqingYu** [comment]
@ByteHamster The OpenAPI YAML spec hasn't specified the fields in the responses yet. No need to update it.

**Comment by ByteHamster** [comment]
I mean this: https://github.com/gpodder/mygpo/blob/1583172764dd8fce74ae443af498291b6adf6df3/mygpo/api/templates/podcasts.xml

In general, if you search for the string, there are some occurrences left: https://github.com/gpodder/mygpo/search?q=subscribers_last_week&type=

The last_subscribers field can probably be removed, here, too: https://github.com/gpodder/mygpo/blob/master/mygpo/api/advanced/directory.py

**Comment by SiqingYu** [comment]
@ByteHamster Thanks for your prudent notice. I've removed them.

**Pull request merged**
